polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings



urlpatterns = patterns('',
    
    url(r'^$','pybursa.views.index', name='index'),
    url(r'^contact/$','pybursa.views.contact', name='contact'),
    url(r'^student_list/$','pybursa.views.student_list', name='student_list'),
    url(r'^student_detail/$','pybursa.views.student_detail', name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace='coaches')),
    url(r'^feedback/$', include('feedbacks.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

students/urls.py
from django.conf.urls import patterns, url

from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    
)

students/models.py
from django.db import models



class Student(models.Model):
    name = models.CharField(max_length=250)
    surname = models.CharField(max_length=250)
    date_of_birth = models.DateField()
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    address = models.CharField(max_length=250)
    skype = models.CharField(max_length=250)
    courses = models.ManyToManyField('courses.Course')

    def __unicode__(self):
        return self.surname

    def my_property(self):
        return u'{} {}'.format(self.name, self.surname)

    my_property.short_description = 'Full name'
    full_name = property(my_property)




    

students/forms.py
from django import forms
from students.models import Student

class StudentModelForm(forms.ModelForm):
    class Meta:
        model = Student 
        exclude = []
        fields = '__all__'

students/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy

from students.models import Student
from courses.models import Course
from students.forms import StudentModelForm
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import logging
logger = logging.getLogger(__name__) # students.views


''' begin Class-based views '''

class StudentListView(ListView):
    model = Student
    paginate_by = 2    

    def get_queryset(self):
        course_id = self.request.GET.get('course_id', None)
        if course_id:
            students_list = Student.objects.filter(courses__id=course_id)
            students_list.order_by('id')
        else:
            students_list = Student.objects.all()
            #current_page = Paginator(students_list, 2)
            students_list.order_by('id')
        return students_list

class StudentDetailView(DetailView):
    model = Student 
    
    def get_context_data(self, **kwargs):
        context = super(StudentDetailView, self).get_context_data(**kwargs)
        logger.debug('Students detail view has been debugged')
        logger.info('Logger of students detail view informs you!')
        logger.warning('Logger of students detail view warns you!')
        logger.error('Students detail view went wrong!')
        return context  

class  StudentCreateView(CreateView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    form_class = StudentModelForm

    def get_context_data(self, **kwargs):
        context = super(StudentCreateView, self).get_context_data(**kwargs)
        context["title"] = "Student registration"

        return context
    
    def form_valid(self,form):
        application = form.save()
        messages.success(self.request, u'Student %s %s has been successfully added.'%(application.name, application.surname))
        return super(StudentCreateView, self).form_valid(form)

class StudentUpdateView(UpdateView):
    model = Student
    success_url = reverse_lazy('students:list_view')
    fields = '__all__' # if empty - rise an error "RemovedInDjango18Warning: Calling modelform_factory...'fields' or 'exclude'..." 

    def get_context_data(self, **kwargs):
        context = super(StudentUpdateView, self).get_context_data(**kwargs)
        context["title"] = "Student info update"
        return context
    
    def form_valid(self,form):
        application = form.save()
        messages.success(self.request, u'Info on the student has been sucessfully changed.')
        return super(StudentUpdateView, self).form_valid(form)

class StudentDeleteView(DeleteView):
    model = Student
    success_url = reverse_lazy('students:list_view')

    def get_context_data(self, **kwargs):
        context = super(StudentDeleteView, self).get_context_data(**kwargs)
        context["title"] = "Student info suppression"
        return context


''' end Class-based views '''

'''
def list_view(request):
    if request.GET:
        course_id = int(request.GET['course_id'])
        course = get_object_or_404(Course, id=course_id)
        students_list = course.student_set.all()
        students_list.order_by('id')
    else:
        students_list = Student.objects.all()
        students_list.order_by('id')

    student_courses = dict()

    for st in students_list:
        student_courses[st.id] = st.courses.all()
        s = {
             'students_list': students_list, 
             'course_list': student_courses
             }
    return render(request, 'students/student_list.html', s)


def detail(request, student_id):
    student = get_object_or_404(Student, id=int(student_id))
    student_courses_list = student.courses.all()
    s = {
         'student':student, 
         'students_courses':student_courses_list
        }
    return render(request, 'students/detail.html', s)


def create(request):
    if request.method == 'POST':
        form = StudentModelForm(request.POST)
        if form.is_valid():
            application = form.save()
            messages.success(request, u'Student %s %s has been successfully added.' % (application.name, application.surname))
            return redirect('students:list_view')
    else:
        form = StudentModelForm()
    return render(request, 'students/add.html', {'form' : form})


def remove(request, student_id):
    student_inst = get_object_or_404(Student, id=student_id)    
    if request.method == 'POST':
        messages.success(request, u'Info on %s %s has been sucessfully deleted.' % (student_inst.name, student_inst.surname))
        student_inst.delete()
        return redirect('students:list_view')
    return render(request,'students/remove.html', {'student': student_inst})


def edit(request, student_id):    
    student_inst = get_object_or_404(Student, id=student_id)    
    if request.method == 'POST':
        form = StudentModelForm(request.POST, instance = student_inst)
        if form.is_valid():
            form.save()
            messages.success(request, u'Info on the student has been sucessfully changed.')
            return redirect('students:list_view')                
    else:
        form = StudentModelForm(instance = student_inst)
    return render(request, 'students/edit.html', {'form': form})

'''

templates/students/add.html
{% extends "base.html" %}
{% block title %}Добавление студента{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Создание нового студента</h2>

    <!--h4>Ниже предоставлен список студентов курса</h4-->
   </div>
<form method="post">
    {% csrf_token %}
    {{form.as_p }}
    <input type="submit" value="Создать"/>
</form>
{% endblock content %}

templates/students/base.html
{% extends "base.html" %}
{% block title %}PyBursa - Students{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
      <div class="page-header">
        <h2>{% block page_header %}{% endblock page_header %}</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
      </div>

<div class="row">
  {% block page_content %}{% endblock page_content %}
  </div>
{% endblock content %}

templates/students/edit.html
{% extends "base.html" %}
{% block title %}Редактирование данных студента{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Редактирование данных студента</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
  </div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Изменить"/>
</form>
{% endblock content %}

templates/students/remove.html
{% extends "base.html" %}
{% block title %}Удаление студента{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Студент {{ student.name }} {{ student.surname }} будет удален</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
  </div>
<form method="post">
     {% csrf_token %}    
    <input type="submit" value="Удалить"/>
</form>
{% endblock content %}

templates/students/student_confirm_delete.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Студент {{ student.name }} {{ student.surname }} будет удален</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
  </div>
<form method="post">
     {% csrf_token %}    
    <input type="submit" value="Удалить"/>
</form>
{% endblock content %}

templates/students/student_detail.html
{% extends "base.html" %}
{% block title %}Student info{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
<div class="page-header">
        <h2>{{student.name}} {{student.surname}}</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
      </div>
 <div class="row">
  <div class="col-md-4">
		<table class="table" >
		<tbody>
		    <tr class="info">
		        <td>дата рождения</td>
		        <td>{{student.date_of_birth|date:'N d, Y'}}</td>
		    </tr>
		            <tr class="info">
		        <td>адрес</td>
		        <td>{{student.address}}</td>
		    </tr>
		            <tr class="info">
		        <td>почта</td>
		        <td>{{student.email}}</td>
		    </tr>
		            <tr class="info">
		        <td>логин skype</td>
		        <td>{{student.skype}}</td>
		    </tr>
		            <tr class="info">
		        <td>телефон</td>
		        <td>{{student.phone}}</td>
		    </tr>
		            <tr class="info">
		        <td>курсы</td>
		        <td>{% for course in student.courses.all %}
		        <p><a href="{% url 'courses:detail' course.id %}">{{course.name}}</a></p>
		        {% endfor %}</td>
		    </tr>
		</tbody>
		</table>
	
	</div>
	</div>
{% endblock content %}

templates/students/student_form.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}{{ title }}{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>{{ title }}</h2>

    <!--h4>Ниже предоставлен список студентов курса</h4-->
   </div>
<div class="col-md-6">
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <input type="submit" value="Создать"/>
</form>
	</div>
{% endblock content %}

templates/students/student_list.html
{% extends "base.html" %}
{% block title %}Студенты курса PyBursa{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}

<br>
{% if messages %}
<div class="well well-sm">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    </div>
{% endif %}
<br>
<a href="{% url 'students:add' %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-plus-sign"></span> Добавить нового студента</a>
<br>

<div class="page-header">
        <h2>Студенты курса PyBursa</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
      </div>
 <!--div class="container"-->
 <div class="row">
  <table class="table">
    <thead>
      <tr>
            <th>#</th>
            <th>фамилия имя</th>
            <th>адрес</th>
            <th>skype</th>
            <th>курсы</th>
        </tr>
    </thead>
    <tbody>
    {% for classman in object_list %}
        <tr class="info">
            <td>{{ classman.id }}</td>
            <td><a href="{% url 'students:detail' classman.id %}">{{ classman.surname }} {{ classman.name }}</a></td>
            <td>{{ classman.address }}</td>
            <td>{{ classman.skype }}</td>
            <td>
            {% for course in classman.courses.all %}
            <p><a href="{% url 'courses:detail' course.id %}">{{ course.name }}</a></p>
            {% endfor %}            
            </td>
            <td>
               <a href="{% url 'students:edit' classman.id %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-pencil"></span>Изменить</a>
            </td>
            <td>
               <a href="{% url 'students:remove' classman.id %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-remove"></span>Удалить</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
  </table>
</div>

{% comment %}
    Paginator_Begin
{% endcomment %}

<div class="text-center">
<ul class="pagination pagination-lg">
   <li>
{% if page_obj.has_previous %}
<li><a href="?page={{ page_obj.previous_page_number }}" aria-label="Previous"><span aria-hidden="true">&laquo; previous</span></a></li>
{% endif %}
{% for sht in page_obj.paginator.page_range %}
    {% if page_obj.number == sht %}
        <li class="active"><a href="?page={{ sht }}">{{ sht }}<span class="sr-only">(current)</span></a></li>
    {% else %}
        <li><a href="?page={{ sht }}">{{ sht }}<span class="sr-only">(current)</span></a></li>
    {% endif %}
{% endfor %}
{% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" aria-label="Next"><span aria-hidden="true">next &raquo;</span></a></li>
{% endif %}

  <!--a href="#" aria-label="Previous">
    <span aria-hidden="true">&laquo;</span>
  </a>
</li>
<li><a href="#">1</a></li>
<li><a href="#">2</a></li>
<li><a href="#">3</a></li>
<li><a href="#">4</a></li>
<li><a href="#">5</a></li>
<li>
  <a href="#" aria-label="Next">
    <span aria-hidden="true">&raquo;</span>
  </a-->
</li>
</ul>
    </div>
{% comment %}
    Paginator_End
{% endcomment %}


{% endblock content %}