courses/urls.py
from django.conf.urls import patterns, url

from courses import views

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^(?P<course_id>\d+)/add_lesson$', views.add_lesson, name='add-lesson'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings



urlpatterns = patterns('',
    
    url(r'^$','pybursa.views.index', name='index'),
    url(r'^contact/$','pybursa.views.contact', name='contact'),
    url(r'^student_list/$','pybursa.views.student_list', name='student_list'),
    url(r'^student_detail/$','pybursa.views.student_detail', name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace='coaches')),
    url(r'^feedback/$', include('feedbacks.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

students/urls.py
from django.conf.urls import patterns, url

from students import views

urlpatterns = patterns('',
    url(r'^$', views.StudentListView.as_view(), name='list_view'),
    url(r'^(?P<pk>\d+)/$', views.StudentDetailView.as_view(), name='detail'),
    url(r'^add/$', views.StudentCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.StudentDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.StudentUpdateView.as_view(), name='edit'),
    
)

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="PyBursa">
    <!--meta name="author" content=""-->
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}PyBursa{% endblock title %}</title>
    
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- link href="/static/css/bootstrap.min.css" rel="stylesheet" -->
    <!-- Bootstrap theme -->
    <!--link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet"-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"-->

    <!-- Custom styles for this template -->
    <!--link href="/static/css/style.css" rel="stylesheet"-->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!--script src="../../assets/js/ie-emulation-modes-warning.js"></script-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body role="document">

    <!-- Fixed navbar -->
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'pybursa.views.index' %}">PYBURSA</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="{% block nav_class_index %}{% endblock %}"><a href="{% url 'index' %}">Main</a></li>            
            <li class="{% block nav_class_contact %}{% endblock %}"><a href="{% url 'contact' %}">Contacts</a></li>
            <li class="{% block nav_class_student %}{% endblock %}"><a href="{% url 'students:list_view' %}">Students</a></li>
            <li class="{% block nav_class_feedback %}{% endblock %}"><a href="{% url 'feedback' %}">Feedback</a></li>
            
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    <!--div-->      
      <!--h1 class="head">Курсы Python от PyBursa</h1-->
      <!--h2 class="head">Description</h2-->
	<!--/div-->

    <div class="container theme-showcase" role="main">
{% block content %}{% endblock content %}
  </div>

      <br />
      <br />
      <hr />


      <div id="footer">
      <div class="container">
        <p class="text-muted credit">Sticky footer <a href="http://pybursa.com"> PyBursa</a></p>
      </div>
    </div>
	<!--/div-->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/docs.min.js' %}"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!--script src="../../assets/js/ie10-viewport-bug-workaround.js"></script-->
  </body>
</html>

templates/contact.html
{% extends "base.html" %}
{% block title %}Contacts{% endblock title %}


{% block nav_class_contact %}active{% endblock %}


{% block content %}

{% include "include/ooun_include.html" %}      
      <div class="page-header">
        <h1>Contacts</h1>
      </div>
      <div class="well">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
      </div>

  <!--address>
      <strong>Twitter, Inc.</strong><br>
      795 Folsom Ave, Suite 600<br>
      San Francisco, CA 94107<br>
      <abbr title="Phone">P:</abbr> (123) 456-7890
  </address-->
     <!-- Director, Manager, Founder -->
    
    <div class="table">
    <ul class="table-row">
        <li class="table-cell">
          <h5><strong>Director</strong></h5>
          <address>    
              <strong>Name: Павел Обод</strong><br />
              <abbr title="Phone">P: </abbr> (123) 456-7890 <br />
              <abbr title="skype">S: </abbr> azaless <br />
              <abbr title="email">E: </abbr><a href="mailto: itbursa100@gmail.com">itbursa100@gmail.com</a>
          </address>

        </li>
        <li class="table-cell">
          <h5><strong>Manager</strong></h5>
          <address>
              <strong>Name: Дария Михалевич</strong><br />
              <abbr title="Phone">P: </abbr> (123) 456-7890 <br />
              <abbr title="skype">S: </abbr> darka.darka.darka.darka. <br />
              <abbr title="email">E: </abbr><a href="mailto: daria.mykhalevych@gmail.com">daria.mykhalevych@gmail.com</a>
          </address>    
        </li>
        <li class="table-cell">
            <h5><strong>Founder</strong></h5>
            <address>
                <strong>Name: Алексей Радченко</strong><br />
                <abbr title="Phone">P: </abbr> (123) 456-7890 <br />
                <abbr title="skype">S: </abbr> dixon.che <br />
                <abbr title="email">E: </abbr><a href="mailto: lenlagun@gmail.com">lenlagun@gmail.com</a>
            </address>
        </li>
    </ul>
  </div>
{% endblock content%}

templates/index.html
{% extends "base.html" %}
{% block title %}Main Page{% endblock title %}


{% block nav_class_index %}active{% endblock %}


{% block content %}

<br>
{% if messages %}
<div class="well well-sm">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    </div>
{% endif %}
<br>

<!-- Main jumbotron for a primary marketing message or call to action -->
      <div class="jumbotron">
      <h1>Курсы от ITBursa</h1>
            <p>Наибольшей проблемой всех учебников и статей, по которым начинают
изучать Python - это отсутствие практики с освоенным материалом.
Можно читать тонны ресурсов по веб-программированию на Python - и
не научиться ничему, потому что знания, которые вы не успели применить,
очень быстро забываются.
Многие начинающие сдаются на полпути, так как устают, им надоедает 
бесконечное блуждание по сети в поисках крупиц информации, из которых
трудно собрать общую картину.</p>
      </div>
<br>
<a href="{% url 'courses:add' %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-plus-sign"></span> Добавить новый курс</a>
<br>

<div class="page-header">
    <h3>Наши курсы</h3>
</div>
      

 <table class="table" >
    <thead>
        <tr class="success">
            <th>Курс</th>
            <th>Описание</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for id_cour, content_cour in course.items %}
        <tr class="info">
            <td><a href="{% url 'courses:detail' id_cour %}">{{ content_cour.0|upper }}</a></td>
            <td>{{ content_cour.1|title }}</td>
            <td>
               <a href="{% url 'courses:edit' id_cour %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-pencil"></span>Изменить</a>
            </td>
            <td>
               <a href="{% url 'courses:remove' id_cour %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-remove"></span>Удалить</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/student_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="PyBursa">
  <!--meta name="author" content=""-->
  <link rel="icon" href="../../favicon.ico">

  <title>Student info</title>
  
  {% load staticfiles %}
  <!-- Bootstrap core CSS -->
  <!--link href="../static/css/bootstrap.min.css" rel="stylesheet"-->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Bootstrap theme -->
  <!--link href="../../dist/css/bootstrap-theme.min.css" rel="stylesheet"-->
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <!--link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet"-->

  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!--link href="../static/css/style.css" rel="stylesheet"-->

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]>
  <script src="../../assets/js/ie8-responsive-file-warning.js"></script>
  <![endif]-->
  <!--script src="../../assets/js/ie-emulation-modes-warning.js">
</script-->

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>

<body role="document">

<!-- Fixed navbar -->
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'pybursa.views.index' %}">PYBURSA</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'pybursa.views.index' %}">Main</a>
        </li>
        <li>
          <a href="{% url 'pybursa.views.contact' %}">Contacts</a>
        </li>
        <li class="active">
          <a href="{% url 'pybursa.views.student_list' %}">Students</a>
        </li>

      </ul>
    </div>
    <!--/.nav-collapse --> </div>
</nav>

<div class="container theme-showcase" role="main">

  <!-- Main jumbotron for a primary marketing message or call to action -->
  <!--div class="jumbotron">
  <h1>К нам можно достучаться если использовать:</h1>
  <p>
    This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.
  </p>
</div-->

<div class="page-header">
  <h1>Ivanov Ivan</h1>
</div>

<!--div class="container"-->
<div class="row">
  <div class="col-md-4">
    <table class="table table-bordered">
      <caption>About student</caption>
      <tbody>

        <tr class="success">
          <td>Surname</td>
          <td>Ivanov</td>

        </tr>
        <tr class="info">
          <td>Name</td>
          <td>Ivan</td>

        </tr>
        <tr class="success">
          <td>Patronymic</td>
          <td>Ivanovich</td>

        </tr>
        <tr class="info">
          <td>Rating</td>
          <td>10</td>

        </tr>
        <tr class="success">
          <td>Average Grade</td>
          <td>90%</td>

        </tr>
        <tr class="info">
          <td>Birth Date</td>
          <td>01/02/1999</td>

        </tr>
        <tr class="success">
          <td>Address</td>
          <td>Украина, г.Харьков</td>

        </tr>
        <tr class="info">
          <td>E-mail</td>
          <td>ivanov.ivan@gmail.com</td>

        </tr>
        <tr class="success">
          <td>Skype</td>
          <td>iivan</td>

        </tr>
      </tbody>
    </table>
  </div>
</div>
<!--/div-->


<div class="row">
  <div class="col-md-5">
    <table class="table table-bordered">
    <caption>Performance</caption>
      <thead>
        <tr class="danger">
          <th>Course</th>
          <th>Week</th>
          <th>Control Type</th>
          <th>Grade</th>
          <!--th>Rating</th-->
        </tr>
      </thead>
      <tbody>
        <tr>
          <td style="vertical-align: middle" class="text" rowspan="3">WEB technologies</td>
          <td style="vertical-align: middle" class="text" rowspan="3">Week 1</td>
          <td>Tests</td>
          <td>100%</td>
          <!--td>Содержимое ячейки9</td-->

        </tr>
        <tr>
          <td>Problem Task №1</td>
          <td>90%</td>
          <!--td>Содержимое ячейки10</td-->
          
        </tr>
        <tr>
          <td>Problem Task №2</td>
          <td>100%</td>
          <!--td>Содержимое ячейки12</td-->
          
        </tr>
        <!--tr>
        <td colspan="2">Содержимое ячейки7</td>
      </tr-->
    </tbody>
  </table>
</div>
</div>

<br />
<br />
<hr />

<div id="footer">
<div class="container">
  <p class="text-muted credit">
    Sticky footer
    <a href="http://pybursa.com">PyBursa</a>
  </p>
</div>
</div>
  </div>

<!-- Bootstrap core JavaScript
    ================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
<!--script src="../static/js/bootstrap.min.js"></script>
<script src="../static/js/docs.min.js"></script-->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/docs.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<!--script src="../../assets/js/ie10-viewport-bug-workaround.js">
</script-->
</body>
</html>

templates/student_list.html
{% extends "base.html" %}
{% block title %}Students{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
      <div class="page-header">
        <h1>Студенты курса PyBursa</h1>
        <h4>Ниже предоставлен список студентов курса</h4>
      </div>

<div class="container">
  <table class="table">
    <thead>
      <tr>
        <th>No</th>
        <th>Surname</th>
        <th>Name</th>
        <th>Address</th>
        <th>Skype</th>
      </tr>
    </thead>
    <tbody>
              
      <tr class="success">
      <td><a href="{% url 'pybursa.views.student_detail' %}">1</a></td>
        <td>Ivanov</td>
        <td>Ivan</td>
        <td>Украина, г.Харьков</td>
        <td>iivan</td>
      </tr>
      <tr class="info">
        <td>2</td>
        <td>Petrov</td>
        <td>Petr</td>
        <td>Украина, г.Харьков</td>
        <td>ppsk</td>
      </tr>
      <tr class="success">
        <td>3</td>
        <td>Sidoroff</td>
        <td>Serg</td>
        <td>Украина, г.Харьков</td>
        <td>skp</td>
      </tr>
      <tr class="info">
        <td>4</td>
        <td>Gladishev</td>
        <td>Alexsander</td>
        <td>Украина, г.Харьков</td>
        <td>aglad</td>
      </tr>
      <tr class="success">
        <td>5</td>
        <td>Golovko</td>
        <td>Maxim</td>
        <td>Украина, г.Харьков</td>
        <td>gmax</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock content %}