courses/urls.py
from django.conf.urls import patterns, url

from courses import views

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', views.CourseDetailView.as_view(), name='detail'),
    url(r'^add/$', views.CourseCreateView.as_view(), name='add'),
    url(r'^remove/(?P<pk>\d+)/$', views.CourseDeleteView.as_view(), name='remove'),
    url(r'^edit/(?P<pk>\d+)/$', views.CourseUpdateView.as_view(), name='edit'),
    url(r'^(?P<course_id>\d+)/add_lesson$', views.add_lesson, name='add-lesson'),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

pybursa/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from django.conf import settings



urlpatterns = patterns('',
    
    url(r'^$','pybursa.views.index', name='index'),
    url(r'^contact/$','pybursa.views.contact', name='contact'),
    url(r'^student_list/$','pybursa.views.student_list', name='student_list'),
    url(r'^student_detail/$','pybursa.views.student_detail', name='student_detail'),
    url(r'^quadratic/', include('quadratic.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^courses/', include('courses.urls', namespace="courses")),
    url(r'^students/', include('students.urls', namespace="students")),
    url(r'^coaches/', include('coaches.urls', namespace='coaches')),
    url(r'^feedback/$', include('feedbacks.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

courses/models.py
from django.db import models
from coaches.models import Coach


class Course(models.Model):
    name = models.CharField(max_length=250)
    short_description = models.CharField(max_length=250)
    description = models.TextField()
    coach = models.ForeignKey(Coach, related_name='coach_courses', null=True, blank=True)
    assistant = models.ForeignKey(Coach, null=True, related_name='assistant_courses', blank=True)


    def __unicode__(self):
        return self.name

class Lesson(models.Model):
    subject = models.CharField(max_length=250)
    description = models.TextField()
    course = models.ForeignKey('Course')
    order = models.PositiveIntegerField()   #serial number

    def __unicode__(self):
        return self.subject

courses/forms.py
from django import forms
from courses.models import Course, Lesson

class CourseModelForm(forms.ModelForm):
    class Meta:
        model = Course
        exclude = []

class LessonModelForm(forms.ModelForm):
    class Meta:
        model = Lesson
        exclude = []

courses/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib import messages
from django.core.urlresolvers import reverse_lazy
from courses.models import Course, Lesson
from courses.forms import CourseModelForm, LessonModelForm

from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

import logging
logger = logging.getLogger(__name__) # courses.views


''' begin Class-based views '''

class CourseDetailView(DetailView):
    model = Course
    template_name = "courses/detail.html"
    context_object_name = "course"
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super(CourseDetailView, self).get_context_data(**kwargs)
        pk = self.kwargs['pk']        
        context["lessons"] = Lesson.objects.filter(course__id = pk)
        logger.debug('Courses detail view has been debugged')
        logger.info('Logger of courses detail view informs you!')
        logger.warning('Logger of courses detail view warns you!')
        logger.error('Courses detail view went wrong!')
        return context

class CourseCreateView(CreateView):
    model = Course
    template_name = 'courses/add.html'
    success_url = reverse_lazy('index')
    fields = '__all__' # if empty - rise an error "RemovedInDjango18Warning: Calling modelform_factory...'fields' or 'exclude'..." 

    def get_context_data(self, **kwargs):
        context = super(CourseCreateView, self).get_context_data(**kwargs)
        context['title'] = u"Course creation"
        return context

    def form_valid(self, form):
        course = form.save()
        messages.success(self.request, u'Course %s has been successfully added.' % course.name)
        return super(CourseCreateView, self).form_valid(form)

class CourseUpdateView(UpdateView):
    model = Course
    fields = '__all__' # if empty - rise an error "RemovedInDjango18Warning: Calling modelform_factory...'fields' or 'exclude'..." 
    template_name = 'courses/edit.html'

    def get_context_data(self, **kwargs):
        context = super(CourseUpdateView, self).get_context_data(**kwargs)
        context['title'] = u"Course update"
        return context

    def get_success_url(self):
        return reverse_lazy('courses:edit', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        messages.success(self.request, 'The changes have been saved.')
        return super(CourseUpdateView, self).form_valid(form)

class CourseDeleteView(DeleteView):
    model = Course
    success_url = reverse_lazy('index')
    template_name = "courses/remove.html"
    
    def get_context_data(self, **kwargs):
        context = super(CourseDeleteView, self).get_context_data(**kwargs)
        context['title'] = "Course deletion"
        return context

    def delete(self, request, pk):
        course = self.get_object()
        msg =  u"Course %s has been deleted." % course.name
        course.delete()
        messages.success(self.request, msg)
        return redirect('index')


''' end Class-based views '''

'''
def detail(request, course_id):
    course_info = get_object_or_404(Course, id=int(course_id))
    lesson_list = Lesson.objects.filter(course_id=course_id)
    lesson_list.order_by('order')
    course_get = '?course_id=%d' % course_info.id
    s = {
         'lessons':lesson_list, 
         'course': course_info, 
         'course_get': course_get
        }
    return render(request, 'courses/detail.html', s)



def add(request):
    if request.method == 'POST':
        form = CourseModelForm(request.POST)
        if form.is_valid():
            application = form.save()
            messages.success(request, u'Course %s has been successfully added.' % (application.name))
            return redirect('index')
    else:
        form = CourseModelForm()
    return render(request, 'courses/add.html', {'form' : form})


def remove(request, course_id):
    course_inst = get_object_or_404(Course, id=course_id)    
    if request.method == 'POST':
        messages.success(request, u'Course %s has been deleted.' % (course_inst.name))
        course_inst.delete()
        return redirect('index')
    return render(request,'courses/remove.html', {'course': course_inst})


def edit(request, course_id):    
    course_inst = get_object_or_404(Course, id=course_id)    
    if request.method == 'POST':
        form = CourseModelForm(request.POST, instance = course_inst)
        if form.is_valid():
            form.save()
            messages.success(request, u'The changes have been saved.')
            return redirect('courses:edit', course_id)                
    else:
        form = CourseModelForm(instance = course_inst)
    return render(request, 'courses/edit.html', {'form': form})

'''
def add_lesson(request, course_id):
    if request.method == 'POST':
        form = LessonModelForm(request.POST)
        if form.is_valid():
            lesson = form.save()
            messages.success(request, u'Lesson %s has been successfully added.' % (lesson.subject))
            return redirect('courses:detail', lesson.course.id)
    else:
        course=Course.objects.get(id=course_id)
        form = LessonModelForm(initial = {'course': course})
    return render(request, 'courses/add_lesson.html', {'form' : form})

templates/courses/add.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}{{ title }}{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Создание нового курса</h2>

    <!--h4>Ниже предоставлен список студентов курса</h4-->
   </div>
<div class="col-md-6">
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <input type="submit" value="Создать"/>
</form>
	</div>
{% endblock content %}

templates/courses/add_lesson.html
{% extends "base.html" %}
{% block title %}Добавление урока{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Создание нового занятия</h2>

    <!--h4>Ниже предоставлен список студентов курса</h4-->
   </div>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Создать"/>
</form>
{% endblock content %}

templates/courses/detail.html
{% extends "base.html" %}
{% block title %}Details about the course{% endblock title %}


{% block nav_class_index %}active{% endblock %}


{% block content %}

<br>
{% if messages %}
<div class="well well-sm">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    </div>
{% endif %}
<br>

  <div class="jumbotron">
        <h1>{{ course.name }}</h1>
      <p>{{ course.description|truncatechars:32 }}</p>
    </div>

{% if course.coach or course.assistant %}

    <div><h4><b>Преподаватели</b></h4></div>
 
{% endif %}

{% if course.coach %}        
    <div class="well well-sm">
    	
      <h5><b>Учитель</b></h5>
  </div>
	   
  <div>
    <a href="{% url 'coaches:detail' course.coach.id %}">{{ course.coach.first_name_field }} {{ course.coach.last_name_field }}</a>
      <p>{{ course.coach.description }}</p>
  </div>

{% endif %}

{% if course.assistant %}
   <div class="well well-sm">
   <h5><b>Ассистент</b></h5> 
  </div>
  <div>   
     <a href="{% url 'coaches:detail' course.assistant.id %}">{{ course.assistant.first_name_field }} {{ course.assistant.last_name_field }}</a>    
      <p>{{ course.assistant.description }}</p>
  </div>   

{% endif %}

<br>
<a href="{% url 'courses:add-lesson' course.id %}" class="btn btn-primary btn-xs" role="button"><span class="glyphicon glyphicon-plus-sign"></span> Добавить занятие</a>
<br>

<div class="page-header">
  <h3>План курса</h3>
  
</div>

<table class="table" >
    <thead>
        <tr class="success">
            <th>#</th>
            <th>Тема</th>
            <th>Описание</th>
        </tr>
    </thead>
    <tbody>
    {% for lesson in lessons %}
        <tr class="info">
            <td>{{ lesson.order }}</td>
            <td>{{ lesson.subject }}</td>
            <td>{{ lesson.description }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock content %}

templates/courses/edit.html
{% extends "base.html" %}
{% load bootstrap %}
{% block title %}{{ title }}{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}

<br>
{% if messages %}
<div class="well well-sm">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
      {% endfor %}
    </ul>
    </div>
{% endif %}
<br>
  <div class="page-header">
    <h2>Редактирование данных курса</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
  </div>
<div class="col-md-6">
<form class="form-horizontal" method="post">
    {% csrf_token %}
    {{ form|bootstrap_horizontal }}
    <input type="submit" value="Изменить"/>
</form>
  </div>
{% endblock content %}

templates/courses/remove.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock title %}


{% block nav_class_student %}active{% endblock %}


{% block content %}
  <div class="page-header">
    <h2>Курс {{ course.name }} будет удален</h2>
        <!--h4>Ниже предоставлен список студентов курса</h4-->
  </div>
<form method="post">
     {% csrf_token %}    
    <input type="submit" value="Удалить"/>
</form>
{% endblock content %}